[package]
name = "micro-scheme-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
ansi_term.workspace = true
ariadne = "0.3.0"
chumsky = "0.9.2"
